[PROTOCOLS]
Virtual Screening = [
	{"tag": "section", "text": "Generic Tasks", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "Protein structure prediction", "openItem": "False", "children": [
	    	    {"tag": "protocol", "value": "ProtESMFoldPrediction",   "text": "default"}
	    ]}
	]}
    ]
